<a href="https://colab.research.google.com/github/JuliaKondratieva/genetic-algorithm-traveling-salesman/blob/main/LAB1_MS%D0%90I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Завдання:

Тема 6. 
Скласти туристичний маршрут між обласними центрами України, так щоб кожне місто відвідувалося лише 1 раз. Якість маршруту - найкоротший маршрут. Відстань між містами можна знайти тут https://109.te.ua/224
Обрати оператори схрещування, та мутації. Дослідити різні рівні мутації та різні методи селекції (елітний (найкращі серед усіх), відбір з витісненням (чи буде особина репродукційної групи входити в нову популяцію, визначається не тільки величиною її пристосованості, а й тим, чи є в новій популяції особина з аналогічним набором хромосом))


In [ ]:
import numpy as np
import random

Distance matrix:

In [ ]:
D=((0,645,868,125,748,366,256,316,1057,382,360,471,428,593,311,844,602,232,575,734,521,120,343,312,396),
(645,0,252,664,81,901,533,294,394,805,975,343,468,196,957,446,430,877,1130,213,376,765,324,891,672),
(868,252,0,858,217,1171,727,520,148,1111,1221,611,731,390,1045,591,706,1100,1391,335,560,988,547,1141,867),
(125,664,858,0,738,431,131,407,1182,257,423,677,557,468,187,803,477,298,671,690,624,185,321,389,271),
(748,81,217,738,0,1119,607,303,365,681,833,377,497,270,925,365,477,977,1488,287,297,875,405,957,747),
(366,901,1171,431,1119,0,561,618,1402,328,135,747,627,898,296,1070,908,134,280,1040,798,246,709,143,701),
(256,533,727,131,607,561,0,298,811,388,550,490,489,337,318,972,346,427,806,478,551,315,190,538,149),
(316,294,520,407,303,618,298,0,668,664,710,174,294,246,627,570,506,547,883,387,225,435,126,637,363),
(1057,394,148,1182,365,1402,811,668,0,1199,1379,857,977,474,1129,739,253,1289,1539,333,806,1177,706,1292,951),
(382,805,1111,257,681,328,388,664,1199,0,152,780,856,725,70,1052,734,159,413,866,869,263,578,336,949),
(360,975,1221,423,833,135,550,710,1379,152,0,850,970,891,232,1173,896,128,261,1028,1141,240,740,278,690),
(471,343,611,677,377,747,490,174,857,780,850,0,120,420,864,282,681,754,999,556,51,590,300,642,640),
(428,468,731,557,497,627,489,294,977,856,970,120,0,540,741,392,800,660,1009,831,171,548,420,515,529),
(593,196,390,468,270,898,337,246,474,725,891,420,540,0,665,635,261,825,1149,141,471,653,279,892,477),
(311,957,1045,187,925,296,318,627,1129,70,232,864,741,665,0,1157,664,162,484,805,834,193,508,331,458),
(844,446,591,803,365,1070,972,570,739,1052,1173,282,392,635,1157,0,896,1097,1363,652,221,964,696,981,1112),
(602,430,706,477,477,908,346,506,253,734,896,681,800,261,664,896,0,774,1138,190,732,662,540,883,350),
(232,877,1100,298,977,134,427,547,1289,159,128,754,660,825,162,1097,774,0,338,987,831,112,575,176,568),
(575,1130,1391,671,1488,280,806,883,1539,413,261,999,1009,1149,484,1363,1138,338,0,1299,1065,455,984,444,951),
(734,213,335,690,287,1040,478,387,333,866,1028,556,831,141,805,652,190,987,1299,0,576,854,420,1036,608),
(521,376,560,624,297,798,551,225,806,869,1141,51,171,471,834,221,732,831,1065,576,0,641,351,713,691),
(120,765,988,185,875,246,315,435,1177,263,240,590,548,653,193,964,662,112,455,854,641,0,463,190,455),
(343,324,547,321,405,709,190,126,706,578,740,300,420,279,508,696,540,575,984,420,351,463,0,660,330),
(312,891,1141,389,957,143,538,637,1292,336,278,642,515,892,331,981,883,176,444,1036,713,190,660,0,695),
(396,672,867,271,747,701,149,363,951,949,690,640,529,477,458,1112,350,568,951,608,691,455,330,695,0))

Const values:

In [ ]:
POPULATION_SIZE=250
P_CROSSOVER=0.9
P_MUTATION=0.0
MAX_GENERATIONS=100

Початкова популяція

In [ ]:
all=[i for i in range (0, len(D))]
copy_all=all.copy()
population=[copy_all]
population=np.array(population)
for i in range (1,POPULATION_SIZE):
  random.shuffle(copy_all)
  population=np.row_stack((population,copy_all))

print(np.array(D).shape)
print(np.array(population).shape)
print(population)

(25, 25)
(250, 25)
[[ 0  1  2 ... 22 23 24]
 [23 14  3 ...  6 15 22]
 [ 7 12 17 ... 11 18 16]
 ...
 [19  6 12 ... 11 15  7]
 [14 16  9 ... 15 22 21]
 [ 9 10 13 ... 19  4 22]]


Пристосованість

In [ ]:
Fitness=np.zeros(POPULATION_SIZE)
for i in range (0,len(population)):
  for j in range (0,len(population[i])-1):
    Fitness[i]+=D[population[i][j]][population[i][j+1]]

print(Fitness)
print(Fitness.shape)
start_population = np.empty((0,26))
for i in range (0,len(population)):
  p=np.append(population[i],Fitness[i])
  #print("P: ",i,p[0])
  start_population=np.row_stack((start_population,p))

print(start_population)

[16164. 17529. 16655. 15797. 16698. 14950. 14807. 14456. 17073. 16187.
 14732. 13684. 13569. 16721. 13413. 12859. 15649. 16651. 15129. 16748.
 14717. 13337. 15734. 14226. 13306. 15523. 14066. 16414. 13784. 15302.
 14405. 14740. 15517. 15390. 14787. 13646. 13939. 14034. 14201. 13779.
 15847. 15299. 16015. 14040. 13188. 14057. 17016. 14510. 14811. 13758.
 15865. 16451. 13983. 15300. 13915. 14441. 12808. 12619. 14800. 14468.
 13550. 16286. 13796. 16548. 14035. 14472. 15213. 13513. 15244. 15953.
 15085. 14221. 16894. 15107. 14891. 15804. 15089. 16133. 15835. 16041.
 13898. 13848. 15506. 15784. 14747. 13073. 14026. 14189. 14713. 15043.
 14565. 14552. 12420. 15212. 12630. 12744. 14749. 13862. 15630. 15768.
 14101. 11920. 15437. 12818. 12573. 15333. 13684. 15739. 16064. 14111.
 14206. 14120. 14407. 12648. 14892. 15786. 15945. 11104. 14548. 15561.
 15153. 16462. 14090. 14234. 13882. 14714. 15612. 14364. 16609. 13170.
 15314. 13045. 15254. 18340. 15301. 16576. 12677. 13698. 15525. 16338.
 13007

In [ ]:
def calc_fitness(hrom):
  fit=0
  for j in range (0,len(hrom)-1):
    fit+=D[int(hrom[j])][int(hrom[j+1])]
  hrom.append(fit)
  return hrom

Вибір батьків:

*("Можна все на світі вибирати, сину, вибрати не можна тільки Батьківщину." (В. Симоненко))*




In [ ]:
def Tournament(population):
    inter_mas = []
    for n in range(POPULATION_SIZE):
        i1 = i2 = i3 = 0
        while i1 == i2 or i1 == i3 or i2 == i3:
            i1, i2, i3 = random.randint(0, POPULATION_SIZE-1), random.randint(0, POPULATION_SIZE-1), random.randint(0, POPULATION_SIZE-1)

        inter_mas.append(min([population[i1], population[i2], population[i3]], key=lambda x: x[len(D)]))

    return inter_mas

Схрещування

In [ ]:
def Crossing(par1, par2):
  p=random.randint(3, len(D[0])-2)
  ch1=[]
  for i in range(0,p):
    ch1.append(par1[i])
  for j in range(p,len(D[0])):
    if not(par2[j] in ch1):
      ch1.append(par2[j])
  if(len(ch1)<len(D[0])):
    for j in range(p,len(D[0])):
      if(not(par1[j] in ch1)):
        ch1.append(par1[j])
  ch1=calc_fitness(ch1)

  ch2=[]
  for i in range(0,p):
    ch2.append(par2[i])
  for j in range(p,len(D[0])):
    if not(par1[j] in ch2):
      ch2.append(par1[j])
  if(len(ch2)<len(D[0])):
    for j in range(p,len(D[0])):
      if(not(par2[j] in ch2)):
        ch2.append(par2[j])
  ch2=calc_fitness(ch2)

  return ch1, ch2

Mutation

In [ ]:
def Mutation(hrom):
  mp=random.randint(0,100)
  if(mp<P_MUTATION*100):
    rg1=random.randint(0,len(hrom)-2)
    rg2=random.randint(0,len(hrom)-2)
    hrom[rg1], hrom[rg2]=hrom[rg2], hrom[rg1]
  return hrom

Головна функція:

In [ ]:
generationCounter = 0
bestFitnessValues = []
while generationCounter < MAX_GENERATIONS:
    generationCounter += 1
    offspring = Tournament(start_population)
    start_population = np.empty((0, 26))

    for p1, p2 in zip(offspring[::2], offspring[1::2]):
        ch1, ch2=p1,p2
        if random.random() < P_CROSSOVER:
            ch1, ch2 = Crossing(p1, p2)
        if random.random() < P_MUTATION:
            ch1 = Mutation(ch1)

        if random.random() < P_MUTATION:
            ch2 = Mutation(ch2)
        #start_population = UpdatePopulation(start_population, ch1, ch2)
        start_population = np.row_stack((start_population, ch1))
        start_population = np.row_stack((start_population, ch2))

    fitnessValues = [ind[len(D)] for ind in start_population]

    bestFitness = min(fitnessValues)

    bestFitnessValues.append(bestFitness)
    print(f"Population N {generationCounter}: Path length = {bestFitness}")

    best_index = fitnessValues.index(min(fitnessValues))
    print("Best route = ", *start_population[best_index], "\n")

Population N 1: Path length = 11129.0
Best route =  2.0 4.0 7.0 16.0 13.0 17.0 0.0 24.0 14.0 3.0 11.0 15.0 23.0 19.0 20.0 1.0 8.0 22.0 21.0 12.0 6.0 9.0 18.0 5.0 10.0 11129.0 

Population N 2: Path length = 10737.0
Best route =  12.0 7.0 11.0 22.0 8.0 2.0 13.0 1.0 15.0 20.0 4.0 14.0 18.0 23.0 10.0 16.0 5.0 9.0 6.0 21.0 3.0 0.0 19.0 17.0 24.0 10737.0 

Population N 3: Path length = 9774.0
Best route =  2.0 7.0 19.0 24.0 17.0 0.0 13.0 11.0 20.0 3.0 14.0 18.0 23.0 10.0 5.0 9.0 6.0 22.0 12.0 21.0 4.0 15.0 1.0 16.0 8.0 9774.0 

Population N 4: Path length = 9748.0
Best route =  19.0 13.0 1.0 6.0 20.0 11.0 4.0 2.0 17.0 21.0 12.0 0.0 3.0 22.0 7.0 24.0 15.0 10.0 14.0 9.0 18.0 5.0 23.0 16.0 8.0 9748.0 

Population N 5: Path length = 9086.0
Best route =  22.0 17.0 24.0 23.0 21.0 0.0 13.0 11.0 20.0 3.0 14.0 18.0 10.0 5.0 9.0 6.0 16.0 8.0 15.0 12.0 4.0 1.0 2.0 7.0 19.0 9086.0 

Population N 6: Path length = 8895.0
Best route =  18.0 10.0 24.0 6.0 20.0 11.0 3.0 14.0 17.0 21.0 12.0 0.0 22.0 7.0 15.0

Найкращий туристичний маршрут:
⛺

In [ ]:
cityIndex = {
  0:"Вінниця",
  1:"Дніпропетровськ",
  2:"Донецьк",
  3:"Житомир",
  4:"Запоріжжя",
  5:"Ів-Франківськ",
  6:"Київ",
  7:"Кіровоград",
  8:"Луганськ",
  9:"Луцьк",
  10:"Львів",
  11:"Миколаїв",
  12:"Одеса",
  13:"Полтава",
  14:"Рівне",
  15:"Сімферополь",
  16:"Суми",
  17:"Тернопіль",
  18:"Ужгород",
  19:"Харків",
  20:"Херсон",
  21:"Хмельницький",
  22:"Черкаси",
  23:"Чернівці",
  24:"Чернігів"
}
print("Optimal route:",start_population[best_index][-1])
for i in start_population[best_index][:-1]:
  print(cityIndex[i])

Optimal route: 5642.0
Ужгород
Львів
Київ
Чернігів
Черкаси
Одеса
Сімферополь
Херсон
Миколаїв
Кіровоград
Чернівці
Ів-Франківськ
Тернопіль
Луцьк
Рівне
Хмельницький
Вінниця
Житомир
Суми
Луганськ
Донецьк
Запоріжжя
Дніпропетровськ
Полтава
Харків


Елітний підхід відбору

Суть этого принципа заключается в том, что в новое поколение включаются лучшие родительские особи. Их число может быть от 1 и больше.

Использование "элитизма" позволяет не потерять хорошее промежуточное решение, но, в то же время, из-за этого алгоритм может "застрять" в локальном экстремуме

In [ ]:
sizeElite=20 #FUN FACT - зі 100 елітними особами у наступному поколінні - результат гірший ніж з 20

generationCounter = 0
bestFitnessValues = []
population=start_population
while generationCounter < MAX_GENERATIONS:
  generationCounter += 1  
  s=sorted(population,key=lambda x: x[len(D)])
  new_popul=np.empty((0,26))
  for i in range(0,sizeElite):
    new_popul=np.row_stack((new_popul,s[i]))
  
  while not len(new_popul)==POPULATION_SIZE:
        i1 = i2 = i3 = 0
        while i1 == i2:
            i1, i2 = random.randint(0, POPULATION_SIZE-1), random.randint(0, POPULATION_SIZE-1)
        c1, c2= Crossing(population[i1], population[i2])
        if random.random() < P_MUTATION:
            c1 = Mutation(c1)

        if random.random() < P_MUTATION:
            c2 = Mutation(c2)
        new_popul=np.row_stack((new_popul,c1))
        new_popul=np.row_stack((new_popul,c2))

  population=new_popul
  fitnessValues = [ind[len(D)] for ind in population]
  
  bestFitness = min(fitnessValues)

  bestFitnessValues.append(bestFitness)
  print(f"Population N {generationCounter}: Path length = {bestFitness}")

  best_index = fitnessValues.index(min(fitnessValues))
  print("Best route = ", *population[best_index], "\n")

Population N 1: Path length = 5642.0
Best route =  18.0 10.0 6.0 24.0 22.0 12.0 15.0 20.0 11.0 7.0 23.0 5.0 17.0 9.0 14.0 21.0 0.0 3.0 16.0 8.0 2.0 4.0 1.0 13.0 19.0 5642.0 

Population N 2: Path length = 5642.0
Best route =  18.0 10.0 6.0 24.0 22.0 12.0 15.0 20.0 11.0 7.0 23.0 5.0 17.0 9.0 14.0 21.0 0.0 3.0 16.0 8.0 2.0 4.0 1.0 13.0 19.0 5642.0 

Population N 3: Path length = 5642.0
Best route =  18.0 10.0 6.0 24.0 22.0 12.0 15.0 20.0 11.0 7.0 23.0 5.0 17.0 9.0 14.0 21.0 0.0 3.0 16.0 8.0 2.0 4.0 1.0 13.0 19.0 5642.0 

Population N 4: Path length = 5642.0
Best route =  18.0 10.0 6.0 24.0 22.0 12.0 15.0 20.0 11.0 7.0 23.0 5.0 17.0 9.0 14.0 21.0 0.0 3.0 16.0 8.0 2.0 4.0 1.0 13.0 19.0 5642.0 

Population N 5: Path length = 5642.0
Best route =  18.0 10.0 6.0 24.0 22.0 12.0 15.0 20.0 11.0 7.0 23.0 5.0 17.0 9.0 14.0 21.0 0.0 3.0 16.0 8.0 2.0 4.0 1.0 13.0 19.0 5642.0 

Population N 6: Path length = 5642.0
Best route =  18.0 10.0 6.0 24.0 22.0 12.0 15.0 20.0 11.0 7.0 23.0 5.0 17.0 9.0 14.0 21.

In [ ]:
print("Optimal route:",population[best_index][-1])
for i in population[best_index][:-1]:
  print(cityIndex[i])

Optimal route: 5283.0
Ужгород
Тернопіль
Київ
Чернігів
Черкаси
Кіровоград
Сімферополь
Херсон
Миколаїв
Одеса
Чернівці
Ів-Франківськ
Львів
Луцьк
Рівне
Хмельницький
Вінниця
Житомир
Полтава
Харків
Суми
Луганськ
Донецьк
Запоріжжя
Дніпропетровськ
